Add extern C to fix the MacOS build
The build for MacOS currently fails with

```
Undefined symbols for architecture arm64:
  "_duckdb_rdkit_duckdb_cpp_init", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
```

The MacOS linker needs the extern C so that the c++ compiler doesn't
add the "_" as a prefix. Then the linker can find "duckdb_rdkit_duckdb_cpp_init"
without the underscore